server:
  port: 8010
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8077/eureka/
spring:
  application:
    name: product-view-service-ribbon
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html; charset=utf-8
    mode: HTML5